### ISSUE TITLE
Why 'Server starting' logs is printed 2 times?

### ISSUE THREAD

**Issue by dhruv-bansal** [sxhxliang/mcp-access-point#5]
Why mcp-access-point is started - following logs are getting printed twice every time

```
[2025-05-18T22:02:38Z INFO  pingora_core::server] Server starting
[2025-05-18T22:02:38Z INFO  pingora_core::server] Server starting
```

Is that means pingora server is running twice?

**Comment by sxhxliang** [comment]
Would you mind sending me your full configuration file?

**Comment by dhruv-bansal** [comment]
Here is the complete config file
```

access_point:
  listeners:
    - address: 0.0.0.0:8080

mcps:
  - id: test
    upstream_id: 1
    path: https://petstore.swagger.io/v2/swagger.json


upstreams:
  - id: 1 
    nodes:
      "127.0.0.1:8091": 1
    scheme: https
    pass_host: preserve
```
