### ISSUE TITLE
[ERROR pingora_proxy] Fail to proxy: Downstream ReadTimedout context: timeout: 60s

### ISSUE THREAD

**Issue by limcheekin** [sxhxliang/mcp-access-point#9]
Hi there,

First of all, thanks for sharing the repo. Nice works!

I deployed the mcp-access-point using the following docker compose file:
```
services:
  mcp-access-point:
    # Build the Docker image from the Dockerfile of the repo.
    build: 
      context: https://github.com/sxhxliang/mcp-access-point.git
    # Name the container.
    container_name: mcp-access-point
    ports:
      # Map port 9999 on the host to port 8080 in the container.
      - "9999:8080"
    environment:
      # Set the internal port for the application.
      - 'port=8080'
    volumes:
      # Mount the local configuration file into the container.
      - ./config.yaml:/app/config/config.yaml
      - ./config/jsonplaceholder:/app/config/jsonplaceholder
    # Restart the service automatically if it fails.
    restart: unless-stopped
```

The following is the config.yaml file:
```
pingora:
  version: 1
  threads: 2
  pid_file: /run/pingora.pid
  upgrade_sock: /tmp/pingora_upgrade.sock
  user: nobody
  group: mcpusers

access_point:
  # listener on TCP or TLS
  listeners:
    - address: 0.0.0.0:8080 # listen on all interfaces
mcps:
  - id: jsonplaceholder # Service identifier
    upstream_id: 1 # Upstream service identifier (must be the same as upstream id in upstreams)
    path: /app/config/jsonplaceholder/swagger.json # Local OpenAPI file path
    upstream: # Upstream service configuration must be defined
      headers: # Headers to send to upstream service
        X-API-Key: "12345-abcdef"        # API key
        Authorization: "Bearer token123" # Bearer token
        User-Agent: "MyApp/1.0"          # User agent
        Accept: "application/json"       # Accept header

upstreams: # Upstream service configuration must be defined
  - id: 1
    headers: # Headers to send to upstream service
      X-API-Key: "12345-abcdef"        # API key
      Authorization: "Bearer token123" # Bearer token
      User-Agent: "MyApp/1.0"          # User agent
      Accept: "application/json"       # Accept header
    nodes: #（e.g., a web server or API server)）
      "jsonplaceholder.typicode.com": 1 # address with weight
    type: roundrobin # Load balancing algorithm (roundrobin, random, ip_hash)
    scheme: https # supports http and https
    pass_host: rewrite # set to rewrite to upstream_host, when nodes are domains
    upstream_host: jsonplaceholder.typicode.com # set to override host header
```

Do you catch any error? May I know why I see `Fail to proxy: Downstream ReadTimedout context: timeout` in the logs of the docker container? I tested with `npx @modelcontextprotocol/inspector node build/index.js` for `http://127.0.0.1:9999/api/jsonplaceholder/mcp`, after connected I click on "List Tools" show `[]`.

The full code to reproduce the errors above located at `jsonplaceholder` branch of https://github.com/limcheekin/mcp-proxy-to-api-nocode/tree/jsonplaceholder

Please advise. Thank you.
